[build]
  publish = "build"
  command = "yarn build"

[context.develop.environment]
    REACT_APP_PUBLIC_URL = "https://develop--dashboard-buyte.netlify.com"
    REACT_APP_FORCE_ENV = "develop-staging"
    REACT_APP_AUTH_URL = "id-dev.buytecheckout.com"
    REACT_APP_FUNCTIONS_URL = "https://connect.dev.buytecheckout.com"